### ISSUE TITLE
Several compatibility and unacceptable security findings activating in RHEL 9 semi disconnected environment

### ISSUE THREAD

**Issue by rseabra** [nextcloud/whiteboard#203]
### Steps to reproduce
1. configure .env with token and Nextcloud URL
2. export *_proxy variables and run npm ci in a setup.sh shell script
3. run sudo -u apache ./setup.sh
4. analyse report complaining about compatibilities, deprecated or replaced packages, vulnerabilities,  25 moderate but many  are actually unacceptable like XSS, and 4 high vulnerabilities.
### Expected behaviour
A reasonably clean result and working conditions

### Actual behaviour
Unacceptable presence of too many vulnerabilities and a non working environment.

### Server configuration

**Web server:** Apache (but didn't get to that point yet)

**Database:** MariaDB (but didn't get to that point yet)

**PHP version:** 8.2

**Nextcloud version:** 30.0.0

<details>
<summary>List of activated apps</summary>

Many but didn't get to that point yet.

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```
</details>

<details>
<summary>Nextcloud configuration</summary>
Disconnected environment with limited external URL access, no failed external requests detected in proxy logs.

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder
```
</details>

**Comment by rseabra** [comment]
Running setup.sh output:

```
sudo -u apache ./setup.sh
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@nextcloud/[moment@1.3.1](mailto:moment@1.3.1)',
npm WARN EBADENGINE   required: { node: '^20.0.0', npm: '^9.0.0' },
npm WARN EBADENGINE   current: { node: 'v20.12.2', npm: '10.5.0' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@nextcloud/[l10n@2.2.0](mailto:l10n@2.2.0)',
npm WARN EBADENGINE   required: { node: '^20.0.0', npm: '^9.0.0' },
npm WARN EBADENGINE   current: { node: 'v20.12.2', npm: '10.5.0' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@nextcloud/[webpack-vue-config@6.0.1](mailto:webpack-vue-config@6.0.1)',
npm WARN EBADENGINE   required: { node: '^20.0.0', npm: '^9.0.0' },
npm WARN EBADENGINE   current: { node: 'v20.12.2', npm: '10.5.0' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@skjnldsv/[sanitize-svg@1.0.2](mailto:sanitize-svg@1.0.2)',
npm WARN EBADENGINE   required: { node: '^14.0.0', npm: '^7.0.0' },
npm WARN EBADENGINE   current: { node: 'v20.12.2', npm: '10.5.0' }
npm WARN EBADENGINE }
npm WARN deprecated [phin@2.9.3](mailto:phin@2.9.3): Package no longer supported. Contact Support at https://www.npmjs.com/support for more info.
npm WARN deprecated [sourcemap-codec@1.4.8](mailto:sourcemap-codec@1.4.8): Please use @jridgewell/sourcemap-codec instead
npm WARN deprecated [inflight@1.0.6](mailto:inflight@1.0.6): This module is not supported, and leaks memory. Do not use it. Check out lru-cache if you want a good and tested way to coalesce async requests by a key value, which is much more comprehensive and powerful.
npm WARN deprecated [rimraf@3.0.2](mailto:rimraf@3.0.2): Rimraf versions prior to v4 are no longer supported
npm WARN deprecated [abab@2.0.6](mailto:abab@2.0.6): Use your platform's native atob() and btoa() methods instead
npm WARN deprecated [domexception@4.0.0](mailto:domexception@4.0.0): Use your platform's native DOMException instead
npm WARN deprecated @humanwhocodes/[object-schema@2.0.3](mailto:object-schema@2.0.3): Use @eslint/object-schema instead
npm WARN deprecated [samsam@1.3.0](mailto:samsam@1.3.0): This package has been deprecated in favour of @sinonjs/samsam
npm WARN deprecated [consolidate@0.15.1](mailto:consolidate@0.15.1): Please upgrade to consolidate v1.0.0+ as it has been modernized with several long-awaited fixes implemented. Maintenance is supported by Forward Email at https://forwardemail.net/ ; follow/watch https://github.com/ladjs/consolidate for updates and release changelog
npm WARN deprecated @humanwhocodes/[config-array@0.11.14](mailto:config-array@0.11.14): Use @eslint/config-array instead
npm WARN deprecated [glob@7.2.3](mailto:glob@7.2.3): Glob versions prior to v9 are no longer supported
npm WARN deprecated [glob@7.2.3](mailto:glob@7.2.3): Glob versions prior to v9 are no longer supported
npm WARN deprecated [glob@7.2.3](mailto:glob@7.2.3): Glob versions prior to v9 are no longer supported
npm WARN deprecated [glob@7.2.3](mailto:glob@7.2.3): Glob versions prior to v9 are no longer supported
npm WARN deprecated [glob@7.2.3](mailto:glob@7.2.3): Glob versions prior to v9 are no longer supported
npm WARN deprecated [glob@7.2.3](mailto:glob@7.2.3): Glob versions prior to v9 are no longer supported
npm WARN deprecated [glob@7.2.3](mailto:glob@7.2.3): Glob versions prior to v9 are no longer supported
npm WARN deprecated [glob@7.2.3](mailto:glob@7.2.3): Glob versions prior to v9 are no longer supported
npm WARN deprecated [glob@7.2.3](mailto:glob@7.2.3): Glob versions prior to v9 are no longer supported
npm WARN deprecated [nextcloud-vue-collections@0.12.0](mailto:nextcloud-vue-collections@0.12.0): This package is now deprecated, the components have been merged into @nextcloud/vue as of version 8.14.0.
npm WARN deprecated [popper.js@1.16.1](mailto:popper.js@1.16.1): You can find the new Popper v2 at @popperjs/core, this package is dedicated to the legacy v1
npm WARN deprecated [sinon@5.0.7](mailto:sinon@5.0.7): 16.1.1
npm WARN deprecated [vue@2.7.16](mailto:vue@2.7.16): Vue 2 has reached EOL and is no longer actively maintained. See https://v2.vuejs.org/eol/ for more details.

added 2305 packages, and audited 2306 packages in 1m

377 packages are looking for funding
  run `npm fund` for details

29 vulnerabilities (25 moderate, 4 high)

To address issues that do not require attention, run:
  npm audit fix

To address all issues possible (including breaking changes), run:
  npm audit fix --force

Some issues need review, and may require choosing
a different dependency.

Run `npm audit` for details.
```

**Comment by rseabra** [comment]
Changed setup.sh to run npm audit fix instead of npm ci:

```
sudo -u apache ./setup.sh
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: [nextcloud@1.0.0](mailto:nextcloud@1.0.0)
npm ERR! Found: [css-loader@6.11.0](mailto:css-loader@6.11.0)
npm ERR! node_modules/css-loader
npm ERR!   dev css-loader@"^6.8.1" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer css-loader@"^7.1.1" from @nextcloud/[webpack-vue-config@6.1.1](mailto:webpack-vue-config@6.1.1)
npm ERR! node_modules/@nextcloud/webpack-vue-config
npm ERR!   dev @nextcloud/webpack-vue-config@"^6.0.1" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR!
npm ERR! For a full report see:
npm ERR! /usr/share/httpd/.npm/_logs/2024-10-04T14_43_34_271Z-eresolve-report.txt

npm ERR! A complete log of this run can be found in: /usr/share/httpd/.npm/_logs/2024-10-04T14_43_34_271Z-debug-0.log
```

[2024-10-04T14_43_34_271Z-eresolve-report.txt](https://github.com/user-attachments/files/17260271/2024-10-04T14_43_34_271Z-eresolve-report.txt)

**Comment by rseabra** [comment]
I'm using Nextcloud 30, and just installed the Whiteboard app with occ :)

Don't take me wrong, I love this, but if even it's own npm ci complains of vulnerabilities, it's is not in an usable state!

**Comment by AndyScherzinger** [comment]
@rseabra all good, I get your point and the newly released v1.0.3 has all versions of updated.

However having npm CI complain about vulnerabilities can happen to at least any point of in timely, so if you do a release basically 1h later a vulnerability could be disclosed and reported by npm so one wouldn't ship new releases whenever a single vulnerability becomes public while just because a lib has a vulnerability doesn't mean the app using it is affected by. With a total of 29 reported vulnerabilities is is obviously bad and I am totally with you.
So the above is just a comment about the the fact that a disclosed vulnerability is is different from it being exploitable.

Nevertheless it should be fix with the ältesten release and we also run such dependency fixes via npm in an automated weekly way.

**Comment by AndyScherzinger** [comment]
Reopened since there is an updated list of dependencies that need to be updated

https://github.com/nextcloud/whiteboard/actions/runs/11229776771/job/31215924848

**Comment by juliushaertl** [comment]
Thanks a lot for your reports. We've double checked the reported vulnerabilities and consider those mostly not applicable in general, but I'll provide some more details here for documentation purposes.

## cookie  <0.7.0
* cookie accepts cookie name, path, and domain with out of bounds characters - https://github.com/advisories/GHSA-pxg6-pf52-xh8x

An automatic fix is not available, as it downgrades various node backend packages to very old versions which breaks functional behaviour.

The fix was released 5 days ago and has not made its way to the upstream dependencies that make use of it. However as we are not using the cookie option in socket.io or our implementation of the backend server, we consider this not applicable. We will update dependencies with the fixed version once available nevertheless of course.


## node-gettext 
* Severity: moderate
* node-gettext vulnerable to Prototype Pollution - https://github.com/advisories/GHSA-g974-hxvm-x689

npm audit tells a fix is available which is not valid, because it just downgrades packages of nextcloud to very old versions from before node-gettext was used which breaks functional behaviour.

In our code base translations are static files served by the server and will only allow the admin to pollute an object which they could do anyways by changing the js files on the server.

https://github.com/nextcloud-libraries/nextcloud-l10n/blob/09f9b8083279269615c482f311eecc55fefb3df9/lib/gettext.ts#L67-L74

## vue-template-compiler  >=2.0.0
* Severity: moderate
* vue-template-compiler vulnerable to client-side Cross-Site Scripting (XSS) - https://github.com/advisories/GHSA-g3ch-rx76-35fx

Not applicable for us since it only affected Vue’s in-browser template compiler while we compile the templates at build time.

No fix available for vue 2, will be resolved once we upgrade to vue 3 which is currently in planning.

---

For reporting security issues in general please follow https://github.com/nextcloud/whiteboard/security/policy next time.

**Comment by rseabra** [comment]
Thanks, mates, in any case the npm part would not start due to these issues, but I'll try again when I update the whiteboard app! :)

@juliushaertl didn't notice it and wasn't aware of a different place for that, using issues seemed natural to me, sorry.
