### ISSUE TITLE
Translations support

### ISSUE THREAD

**Issue by juliushaertl** [nextcloud/whiteboard#50]
We should get the current user language from the `@nextcloud/l10n` package and map it to the ones available in excalidraw

https://docs.excalidraw.com/docs/@excalidraw/excalidraw/api/props/#langcode

**Comment by juliushaertl** [comment]
@hweihwang  Mabye you can take over looking into that since Salim is currently out?

**Comment by Jerome-Herbinet** [comment]
@juliushaertl @hweihwang can you give some more details about the future translation possibilities of the tool ? I assume that, in the Nextcloud UI, only a few wordings will have to be translated : 

- "New whiteboard" in Files
- Some wordings in the "Whiteboard" admin section
Will this all be brought soon to Transifex ?

And concerning the Excalidraw UI ; is it displayed in English despite my Nextcloud user is in French because : 

- Excalidraw is only available in English
- Excalidraw exists in French, but something has to be set up on our Excalidraw dedicated server ? In this case, could we hope that the Excalidraw UI language automatically fits de Nextcloud user UI language ?

Thanks
