### ISSUE TITLE
Saving issues

### ISSUE THREAD

**Issue by juliushaertl** [nextcloud/whiteboard#60]
It seems we still have hardcoded dev environemnt credentials for saving back the file. We should instead rather also use the JWT token there, as currently saving fails with that.

**Comment by hweihwang** [comment]
@juliushaertl 

Thanks for pointing this out!

To clarify, are we aiming for BE to BE communication (Node => Nextcloud PHP)? Since the roomData is already validated and authenticated at the time of writing.

If we use JWT for writing, we should consider the following:
- Which JWT to use (from whom), as roomData is shared among all joiners. Perhaps we could use the last joiner's JWT to avoid writing to the file on every socket event.
- Handling JWT expiration during the write process.
- Whether authentication is necessary when saving roomData from Node to Nextcloud BE.

```js
// Called when there's nobody in the room (No one keeping the latest data), BE to BE communication
export const saveRoomDataToFile = async (roomID, data) => {
	console.log(`[${roomID}] Saving room data to file: ${roomID}`)
	const url = `${NEXTCLOUD_URL}/index.php/apps/whiteboard/${roomID}`
	const body = { data: { elements: data } }
	const options = fetchOptions('PUT', '', body)

	await fetchData(url, options)
}

// TODO: Should be called when the server is shutting down and a should be a BE to BE (or OS) communication
//  in batch operation, run in background and check if it's necessary to save for each room.
//  And can be called periodically and saved somewhere else for preventing data loss (memory loss, server crash, electricity cut, etc.)
export const saveAllRoomsData = async () => {
}
```

**Comment by juliushaertl** [comment]
Thanks for the good summary. As discussed in the call let's go for a shared token authentication so the node backend can authenticate towards the PHP backend with that. We should keep track of users on the board and save the file in the scope of a random user (maybe the last one with edit permissions) as the file system currently does not support saving in scope of an app or multiple users.
